
  <div class="static-pages">
    <div class="ui-grid-a mb20">
      <h2 class="ui-block-a per50 mb15 mt5">TERMS OF USE AGREEMENT</h2>
    <a href="javascript:void(0);" onclick="goBack()" data-ajax='false' data-role="button" data-icon="arrow-l" data-inline="true" data-theme="a" class="ui-block-b m0 per35 fRight smallFont">Back</a>
    </div>
    <ol>
      <li>
        <p>Agreement.  We, My Diabetes Home, LLC, run a service called My Diabetes Home or MyDiabetesHome.com.  The following terms and conditions govern all use of the My Diabetes Home website and all content, services and products available at or through the website (taken together, the Website). The Website is owned and operated by My Diabetes Home, LLC. The Website is offered subject to your acceptance without modification of all of the terms and conditions contained herein and all other operating rules, policies (including, without limitation, My Diabetes Home’s Privacy Policy) and procedures that may be published from time to time on this Site by My Diabetes Home (collectively, the “Agreement”).</p>
        <p>By accessing, viewing, and using this Website, “You” (or “Your”) agree to be bound by all the terms and conditions of this Agreement and do hereby enter into the Agreement with My Diabetes Home of this site of Your own free will, are of competent age and mental state, and are otherwise fully capable and qualified to be bound.  These Terms of Use are subject, without notice, to change and modification from time to time.  Your agreement to be bound shall extend to the Terms of Use as they now exist or as they are modified and/or changed.</p>
        <p>IF YOU DO NOT AGREE TO BE BOUND THEN YOU ARE REQUIRED TO CEASE ALL USE OF THE WEBSITE AND ITS CONTENT. </p>
        <p class="mb0">IF YOU HAVE INSTALLED A MY DIABETES HOME PRODUCT/APPLICATION ON ANY MOBILE DEVICE, YOU MUST REMOVE THE PRODUCT/APPLICATION FROM YOUR DEVICE AND CEASE ALL USE OF THE SOFTWARE.</p>
      </li>
      <li>Website License.  My Diabetes Home grants to You, and You do hereby accept, a limited, nontransferable, revocable license to access and make personal use of this Website and not to download (other than for page caching), modify, alter, adjust, change, or amend the Website in any way.  This license does not include:
      <ul class="mt15 mb20">
         <li>the right to resale or commercially use this Website or its contents; or the right to make any collection and use of any content, postings, or viewable materials, listings, or descriptions;</li>
         <li>the right to make any derivative use of this site or its contents;</li>
         <li>the right to any downloading or copying of information for the benefit of another merchant;</li>
         <li>the right to use data mining, robots, spider, offline readers, or similar data gathering and extraction tools;  </li>
         <li>the right to reproduce, duplicate, copy, sell, resell, sublicense, or otherwise exploit the site or any portion of this site for any commercial purpose except as set forth herein;</li>
         <li>the right to frame or utilize framing techniques to enclose any trademark, logo, or other proprietary information (including images, text, page layout, or form) of My Diabetes Home; or</li>
         <li>the right to use any meta tags or any other "hidden text" utilizing My Diabetes Home’s name or trademarks. </li>
         <li>the right to use the Website for unauthorized or unsolicited junk, bulk email, or spamming.</li>
         <li>the right to reverse engineer or otherwise decipher, decompile or derive any source code or underlying algorithms or ideas of any part of the Website. </li>
      </ul>
      <p class="mb0">Engaging in any unauthorized use terminates the permission or license granted herein.</p>
      </li>
      <li>Copyrights.  All content (other than profile information provided by the User), compilation of content, and software included or used on this site, such as text, graphics, logos, button icons, images, audio clips, digital downloads, data compilations, is the property of My Diabetes Home or its content suppliers and are protected by United States and international copyright laws.  You hereby agree not to make any use of any of the copyrighted material or content appearing on this site, without the express written permission of My Diabetes Home.</li>
      <li>Trademarks.  My Diabetes Home’s trademarks, identified on this site with a TM or ®, are the exclusive property of My Diabetes Home.  All other trademarks not owned by My Diabetes Home that appear on this site are the property of their respective owners, who may or may not be affiliated with, connected to, or sponsored by My Diabetes Home.  You hereby agree not to make any use of any of the trademarks appearing on this site, without the express written permission of My Diabetes Home.</li>
      <li>
        Personal Information.  You hereby agree and acknowledge that My Diabetes Home may utilize electronic means of information capture and usage such as cookies, domain name and host capture, browser software capture, IP address capture, and the like.  My Diabetes Home reserves the right to collect and use such information in accordance with generally accepted industry practices.  If You actively submit personal information to My Diabetes Home, My Diabetes Home shall use commercially reasonable efforts to safeguard and protect such information and to use such information only for the purposes intended; however, YOU ACKNOWLEDGE THAT THE SUBMISSION OF PERSONAL INFORMATION IS AT YOUR RISK AND THAT THE PROPRIETOR WAIVES ALL WARRANTIES AND LIMITS ALL LIABILITY ASSOCIATED WITH SUCH INFORMATION TO THE FULLEST EXTENT PERMITTED UNDER THE LAW.
      </li>
      <li><p> Disclaimer of Warranties and Waivers.  THIS SITE IS PROVIDED "AS IS" THE PROPRIETOR MAKES NO WARRANTY OF ANY KIND WITH REGARD TO THE PRODUCTS, CONTENT, SOFTWARE, INFORMATION, OR SERVICES PROVIDED HEREIN, ALL SUCH EXPRESS OR IMPLIED WARRANTIES ARE EXPRESSLY WAIVED TO THE FULLEST EXTENT ALLOWED BY LAW, INCLUDING, WITHOUT LIMITATION, WARRANTIES OF FITNESS FOR PARTICULAR PURPOSE AND WARRANTIES OF MERCHANTABILITY.  THE PROPRIETOR DOES NOT WARRANT THAT THE SITE IS FREE FROM COMPUTER VIRUSES OR OTHER HARMFUL ELECTRONIC OBJECTS AND COMPONENTS.  THE PROPRIETOR SHALL NOT BE LIABLE TO THE USER FOR ANY DAMAGES OF ANY KIND ARISING OUT OF THE USE OF THE SITE, INCLUDING, WITHOUT LIMITATION, PUNITIVE, DIRECT, INDIRECT, INCIDENTAL, AND CONSEQUENTIAL DAMAGES.  AS TO THE OPERATION OF THIS SITE OR THE INFORMATION, CONTENT, MATERIALS, OR PRODUCTS INCLUDED ON THIS SITE, USER EXPRESSLY AGREES THAT USER’S USE OF THIS SITE IS AT USER’S SOLE RISK.</p>
      <p class="mb0">YOU UNDERSTAND THAT WHEN USING THE WEBSITE, YOU WILL BE EXPOSED TO MATERIAL THAT MAY BE OR IS INACCURATE, OFFENSIVE, INDECENT, OR OBJECTIONABLE TO YOU.  MY DIABETES HOME IS NOT RESPONSIBLE FOR THE FOREGOING AS WELL AS ACCURACY, USEFULNESS, SAFETY, OR INTELLECTUAL PROPERTY RIGHTS OF OR RELATING TO USER SUBMISSIONS.  YOU HEREBY AGREE TO WAIVE ANY AND ALL LEGAL OR EQUITABLE RIGHTS OR REMEDIES THAT YOU MAY HAVE OR MAY HAVE AGAINST MY DIABETES HOME WITH RESPECT THERETO.</p></li>
      <li>
        Indemnification.  You agree to indemnify and hold My Diabetes Home harmless from any claim or demand, including reasonable attorneys' fees, made by any third party due to or arising out of Your breach of this Agreement, Your use of this Website or Your violation of any law or the rights of any third party.
      </li>
      <li>Applicable Law.  By visiting this site, You agree that any disputes concerning or involving these Conditions of Use, or the use of this site, shall be governed in accordance with the laws of the State of Iowa.  You hereby consent to the personal jurisdiction of the courts of the State of Iowa for resolution of all disputes concerning or involving this Agreement, or Your use of this Website.</li>
      <li>Amendment.  My Diabetes Home reserves the right to amend this Agreement at any time, by posting on this Website said amended Agreement, Your use and continued use of this Website is deemed an agreement to be bound by any such Amendments.</li>
      <li> Limitations On Actions.  YOU AGREE THAT ANY CAUSE OF ACTION THAT MAY ARISE, RESULT, OR OCCUR AS A RESULT OF YOUR USE OF THE WEBSITE, OR FROM ENTERING INTO THIS AGREEMENT, MUST BE COMMENCED NOT LONGER THAN ONE (1) YEAR FROM THE DATE SUCH CAUSE OF ACTION ACCRUES, OTHERWISE YOU WAIVE ALL RIGHT TO BRING SUCH CAUSE OF ACTION AND SUCH ACTION IS FOREVER BARRED AND DISCHARGED.</li>
      <li>Transferability.  Your agree that Your rights and obligations under this Agreement may not be transferred, assigned, licensed, or otherwise alienated without the express written permission of My Diabetes Home, wherein said permission may be denied for any reason.  </li>
      <li>Reporting Copyright Violations.  If you are believe that a User of the Website has violated or is violating your copyright rights due to that User’s illegal, unlawful, or otherwise improper conduct, you (the copyright owner) or your agent may submit a notification pursuant to the Digital Millennium Copyright Act 17 U.S.C. § 512(c)(3) ("DMCA") by providing our Copyright Agent with the following information in writing: 
      <ul>
         <li> a physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed; </li>
         <li>identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works at a single online site are covered by a single notification, a representative list of such works at that site; </li>
         <li>identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled and information reasonably sufficient to permit the service provider to locate the material;</li>
         <li>information reasonably sufficient to permit the service provider to contact You, such as an address, telephone number, and, if available, an electronic mail; </li>
         <li>a statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and </li>
         <li>a statement that the information in the notification is accurate, and under penalty of perjury, that you are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed. </li>
      </ul>
      <p>You acknowledge that if you fail to comply with all of these requirements, your DMCA notice may not be valid.</p>
      <p class="mb0">My Diabetes Home’s designated Agent to receive notifications of claimed infringement is: <br>
      Emily Harris<br>
Attorney and Designated Agent for My Diabetes Home <br>
Davis Brown Law Firm<br>
215 10th Street, Ste. 1300 <br>
Des Moines, Iowa 50309<br>
Telephone: 515-288-2500<br>
Facsimile: 515-243-0654<br>
Email: emilyharris@davisbrownlaw.com </p>
   <p>Failure to comply with all of the requirements of the foregoing, may result in the waiver or invalidity of the DMCA.  You may be liable for damages, including court costs and attorneys fees if you materially misrepresent that content on the Website constitutes copyright infringement.</p>
   <p>My Diabetes Home will advise the alleged infringer of the DMCA statutory counter-notification procedure as described in the DMCA, at which time the alleged infringer may respond to your claim and ask that the content at issue be restored.  </p>
   <p>Upon receiving your notification of alleged copyright infringement, as set forth above, My Diabetes Home will remove or disable access to the allegedly infringing material and promptly notify the alleged infringer of your claim.  In accordance with the DMCA, My Diabetes Home has implemented a policy to terminated, when appropriate, access to the Website of any repeat infringer.  As stated above, My Diabetes Home may terminate the access of any User at any time for any or no reason.</p>
      </li>
      <li>Links and Third Party Websites. We have not reviewed, and cannot review, all of the material, including computer software, made available through the websites and webpages to which MyDiabetesHome.com links, and that link to MyDiabetesHome.com, and that have been posted to microblogging services through the My Diabetes Home.com software. My Diabetes Home does not have any control over those websites and webpages, and is not responsible for their contents or their use. By linking to a website or webpage, My Diabetes Home does not represent or imply that it endorses such website or webpage. You are responsible for taking precautions as necessary to protect yourself and your computer systems from viruses, worms, Trojan horses, and other harmful or destructive content. My Diabetes Home disclaims any responsibility for any harm resulting from your use of non-WordPress websites and webpages.</li>
      <li> Privacy Policy.  You agree to be bound by the Privacy Policy found at [fill in link], which is incorporated into this Agreement by reference as if fully set forth herein.</li>
      <li>Ability to Accept Terms of Service.  You affirm that you are either more than 18 years of age, or an emancipated minor, or possess legal parental or guardian consent, and are fully able and competent to enter into the terms, conditions, obligations, affirmations, representations, and warranties set from in these Terms of Service, and to abide by and comply with these Terms of Service.  In any case, you affirm that you are over the age of 13, as the Website is not intended for children under 13.  If you are under 13 years of age, please do not use the Website.</li>
      <li>Your Account. If you create an account on the Website, you are responsible for maintaining the security of your account, and you are fully responsible for all activities that occur under the account. You must immediately notify My Diabetes Home of any unauthorized uses of your account or any other breaches of security. My Diabetes Home will not be liable for any acts or omissions by You, including any damages of any kind incurred as a result of such acts or omissions.</li>
      <li>Responsibility of Website Visitors. My Diabetes Home has not reviewed, and cannot review, all of the material, including links to computer software, posted to the Website, and cannot therefore be responsible for that material’s content, use or effects. By operating the Website, My Diabetes Home does not represent or imply that it endorses the material there posted, or that it believes such material to be accurate, useful or non-harmful. You are responsible for taking precautions as necessary to protect yourself and your computer systems from viruses, worms, Trojan horses, and other harmful or destructive content. The Website may contain content that is offensive, indecent, or otherwise objectionable, as well as content containing technical inaccuracies, typographical mistakes, and other errors. The Website may also contain material that violates the privacy or publicity rights, or infringes the intellectual property and other proprietary rights, of third parties, or the downloading, copying or use of which is subject to additional terms and conditions, stated or unstated. My Diabetes Home disclaims any responsibility for any harm resulting from the use by visitors of the Website, or from any downloading by those visitors of content there posted.</li>
      <li> Security.  You are solely responsible for the data provided by You to the Website, including its accuracy and security.  In the event My Diabetes Home reasonably becomes aware of a security breach, including the unauthorized access of a User’s data utilizing the My Diabetes Home Application which is not deemed to be a breach initiating with the User, then My Diabetes Home will provide notice to the User of such breach within 30 days of becoming aware of such breach.   Such notice may be provided by e-mail or letter sent by regular mail to the contact information placed on file with My Diabetes Home.  My Diabetes Home is not responsible for any damages relating to the improper utilization of data or breach of security provisions. </li>
      <li> Intellectual Property. This Agreement does not transfer from My Diabetes Home to you any My Diabetes Home or third party intellectual property, and all right, title and interest in and to such property will remain (as between the parties) solely with My Diabetes Home. Any trademarks, service marks, graphics and logos used in connection with the Website may be the trademarks of My Diabetes Home or other third parties. Your use of the Website grants you no right or license to reproduce or otherwise use any My Diabetes Home or third-party trademarks.</li>
      <li>Medical Information/Disclaimer.  While there may be information on the Website related to certain medical conditions and their symptoms, side effects and treatment, along with information about particular medications, should a medical condition exist, promptly see your health care provider.  My Diabetes Home does not, under any circumstances, offer a personalized medical diagnosis or patient-specific treatment advice.  Material contained on this site or listed as a reference is a general review of the issues, and must not be considered as a substitute for sound medical advice from your personal provider on Your own independent situations. YOU MUST CONSULT WITH YOUR PHYSICIAN OR OTHER QUALIFIED HEALTH CARE PROFESSIONAL BEFORE USING ANY PRODUCT OR SERVICE OR OTHERWISE USING ANY MATERIAL DISCUSSED WITHIN THIS WEBSITE.</li>
      <li>Termination. My Diabetes Home may terminate your access to all or any part of the Website at any time, with or without cause, with or without notice, effective immediately. If you wish to terminate this Agreement or your MyDiabetesHome.com account (if you have one), you may simply discontinue using the Website. All provisions of this Agreement which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.</li>
      <li>Lexicomp.  This Application/product/website utilizes the Lexicomp IntegratedTM platform, which contains information provided by Lexi-Comp, Inc. (D.B.A. Lexicomp) and/or Multum, Inc (collectively “Providers”).  The information contained herein does not endorse drugs, diagnose patients, or recommend therapy.  It is not intended to cover all possible uses, directions, precautions, warnings, drug interactions, allergic reactions, or adverse effects.  If you have questions about the drugs you are taking, check with your doctor, nurse or pharmacist.  In addition, the drug information contained herein may be time sensitive.  This information has been compiled for use by healthcare practitioners and End-Users in the United States.  Neither Providers nor any of their affiliates warrant that uses outside of the United States are appropriate.  Lexicomp does not assume any responsibility for any aspect of healthcare administered with the aid of information Providers supply.</li>
      <li> General Representation and Warranty. You represent and warrant that (i) your use of the Website will be in strict accordance with the My Diabetes Home Privacy Policy, with this Agreement and with all applicable laws and regulations (including without limitation any local laws or regulations in Iowa regarding online conduct and acceptable content, and including all applicable laws regarding the transmission of technical data exported from the United States or the country in which you reside) and (ii) your use of the Website will not infringe or misappropriate the intellectual property rights of any third party.</li>
      <li>Miscellaneous. This Agreement constitutes the entire agreement between My Diabetes Home and you concerning the subject matter hereof, and there may only be modified by a written amendment signed by an authorized executive of My Diabetes Home, or by the posting by My Diabetes Home of a revised version. If any part of this Agreement is held invalid or unenforceable, that part will be construed to reflect the parties’ original intent, and the remaining portions will remain in full force and effect. A waiver by either party of any term or condition of this Agreement or any breach thereof, in any one instance, will not waive such term or condition or any subsequent breach thereof. You may assign your rights under this Agreement to any party that consents to, and agrees to be bound by, its terms and conditions; My Diabetes Home may assign its rights under this Agreement without condition. This Agreement will be binding upon and will inure to the benefit of the parties, their successors and permitted assigns.</li>
    </ol>
  </div>
